### ISSUE TITLE
refinerycms-authentication-devise doesn't play well with activeadmin

### ISSUE THREAD

**Issue by ogerman** [refinery/refinerycms-authentication-devise#16]
Overriding Devise default settings [here](https://github.com/refinery/refinerycms-authentication-devise/blob/master/lib/refinery/authentication/devise/initialiser.rb#L34) and [here](https://github.com/refinery/refinerycms-authentication-devise/blob/master/lib/refinery/authentication/devise/initialiser.rb#L227) brings to [errors](https://github.com/activeadmin/activeadmin/issues/4204) in activeadmin gem

**Comment by bricesanchez** [comment]
Could you provide a pull request to improve the support of activeadmin gem ?

**Comment by bricesanchez** [comment]
Any idea @parndt ?

**Comment by parndt** [comment]
Not immediately.

**Comment by parndt** [comment]
This is why we extracted it though - issues like this

**Comment by eneeyac** [comment]
Does anyone have any thoughts how to fix this issue? Maybe not implementation, but just an idea, which can be implemented by someone else.

**Comment by bricesanchez** [comment]
@eneeyac You could create your own authentication plugin based on the `refinerycms-authentication-devise` and https://github.com/refinerycms-contrib/spree-refinery-authentication

**Comment by eneeyac** [comment]
@bricesanchez Thank you

**Comment by bricesanchez** [comment]
Your welcome
