### ISSUE TITLE
Devise :async

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms-authentication-devise#21]
What is a best way to add :async option in User's model `devise` call?
Should I override whole the call from decorator, like:

```
devise :database_authenticatable, :registerable, :recoverable, :rememberable,
                 :trackable, :validatable, authentication_keys: [:login], :async
```

**Comment by bricesanchez** [comment]
Using `decorator` is probably the best option. Let me know if it works.

**Comment by sintro** [comment]
I will test later, if it works. Actually, now there are no "confirmable" option in User model, so the :async option is almost useless without it (it only needed to send the emails, and now the only way to send the email from Refinery\`s User controller is to make the password recovery). So I will try to add both this options and let you know.
The main interest for me now is to make both administrators and front-end users be powered by Refinery::Authentication::Devise::User model... Don`t sure if it is a good idea, or may be it is better to have two separate devise models.

**Comment by parndt** [comment]
In the past I've generated a new extension for front end users, as it only took an hour or so to get set up
