### ISSUE TITLE
Dependency issue using authentication-devise gem with edge version of RefineryCMS

### ISSUE THREAD

**Issue by frankyn** [refinery/refinerycms-authentication-devise#33]
Hi! 

While using the Edge version of RefineryCMS with Rails 4.2.8 to generate a new RefineryCMS project I hit the dependency conflict shown below. I was able to resolve the issue by using the master branch of this repository. 

(if reasonable) As a request, it would be helpful if `refinerycms-authentication-devise` gem was released with the [dependency version range](https://github.com/refinery/refinerycms-authentication-devise/blob/master/refinerycms-authentication-devise.gemspec#L16) which would accept `refinerycms-core 4.0.0.dev`.

```
Bundler could not find compatible versions for gem "refinerycms-core":
  In Gemfile:
    refinerycms was resolved to 4.0.0.dev, which depends on
      refinerycms-core (= 4.0.0.dev)

    refinerycms was resolved to 4.0.0.dev, which depends on
      refinerycms-core (= 4.0.0.dev)

    refinerycms was resolved to 4.0.0.dev, which depends on
      refinerycms-core (= 4.0.0.dev)

    refinerycms was resolved to 4.0.0.dev, which depends on
      refinerycms-core (= 4.0.0.dev)

    refinerycms-authentication-devise (~> 1.0.4) was resolved to 1.0.4, which depends on
      refinerycms-core (>= 3.0.0, ~> 3.0)

    refinerycms-wymeditor (>= 1.0.6, ~> 1.0) was resolved to 1.1.0, which depends on
      refinerycms-core (< 5.0, >= 3.0.0)
```

**Comment by bricesanchez** [comment]
Edge version of Refinery should be used with Rails 5.1 but it's not yet merged. 

You should use 3-0-stable branch for a Rails 4.2.x project :)

**Comment by frankyn** [comment]
Follow-up:

The reason I used the master branch of `refinerycms` is to use version 1.1.0 of the Dragonfly gem without modifying the gem source. I reviewed branch 3-0-stable and [it does use version 1.1.0](https://github.com/refinery/refinerycms/blob/3-0-stable/resources/refinerycms-resources.gemspec#L23), but the latest tagged version 3.0.5 for RefineryCMS [doesn't have this update](https://github.com/refinery/refinerycms/blob/3.0.5/resources/refinerycms-resources.gemspec#L23).

Question, will a new patch be released with this update soon?

Thanks @bricesanchez!

**Comment by bricesanchez** [comment]
Yes we will release 3.0.6 ASAP. So for now you could use Refinery like this in your Gemfile:

```ruby
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: '3-0-stable'
```

**Comment by frankyn** [comment]
SG, Thanks!
